'use client';
import { useState } from 'react';
import Link from 'next/link';
type Room = { id: string; title: string; lastMessage?: string | null; mentioned?: boolean };
export default function EventChatDrops({ eventKey, title, isLoggedIn }: { eventKey: string; title: string; isLoggedIn: boolean }) {
  const [rooms, setRooms] = useState<Room[]>([]); const [open, setOpen] = useState(false); const [creating, setCreating] = useState(false); const [roomTitle, setRoomTitle] = useState(''); const [accessMode, setAccessMode] = useState('public'); const [error, setError] = useState('');
  const load = () => fetch(`/api/chat/rooms?eventKey=${encodeURIComponent(eventKey)}`, { cache: 'no-store' }).then((r) => r.json()).then((d) => setRooms(d.rooms || [])).catch(() => undefined);
  const requireLogin = () => window.dispatchEvent(new CustomEvent('pl-need-auth', { detail: { next: '/home' } }));
  const create = async () => { if (!isLoggedIn) return requireLogin(); const res = await fetch('/api/chat/rooms', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ title: roomTitle || `Room · ${title}`, eventKey, accessMode }) }); const data = await res.json(); if (!res.ok) return setError(data.error || 'Không tạo được room'); setCreating(false); setRoomTitle(''); setOpen(true); await load(); };
  const unread = rooms.filter((x) => x.mentioned).length;
  return <div className="relative flex items-center gap-1.5">
    <button type="button" onClick={() => isLoggedIn ? setCreating(true) : requireLogin()} className="rounded-full border px-2.5 py-1 text-[11px] font-bold" style={{ borderColor: 'rgba(34,211,238,.35)', background: 'rgba(255,255,255,.52)', color: 'var(--pl-text)' }}>＋ Room</button>
    <button type="button" onClick={() => { setOpen((v) => !v); if (!open && rooms.length === 0) void load(); }} className="pl-chat-drop relative flex h-9 min-w-9 items-center justify-center rounded-[55%_45%_55%_45%] px-2 text-xs font-black shadow-md" aria-label="Mở các room chat">💧{unread || rooms.length || ''}</button>
    {(open || creating) && <div className="pl-future-card absolute right-0 top-11 z-30 w-[min(82vw,320px)] p-3 shadow-xl"><div className="mb-2 flex items-center justify-between"><b className="truncate text-sm">Chat · {title}</b><button type="button" onClick={() => { setOpen(false); setCreating(false); }}>×</button></div>{creating ? <div className="space-y-2"><input autoFocus value={roomTitle} onChange={(e) => setRoomTitle(e.target.value)} maxLength={50} placeholder="Tên room" className="pl-future-input w-full rounded-lg border p-2 text-sm" /><select value={accessMode} onChange={(e) => setAccessMode(e.target.value)} className="pl-future-input w-full rounded-lg border p-2 text-sm"><option value="public">Công khai</option><option value="private">Riêng tư</option></select>{error && <p className="text-xs text-red-600">{error}</p>}<button type="button" onClick={() => void create()} className="ev-publish w-full rounded-lg p-2 text-sm font-bold">Tạo room</button></div> : <div className="max-h-64 space-y-2 overflow-auto">{rooms.length ? rooms.map((r) => <Link key={r.id} href={`/chat/${r.id}`} className="block rounded-xl p-2 text-sm no-underline" style={{ background: 'var(--pl-surface-soft)' }}><b>{r.title}</b>{r.lastMessage && <span className="block truncate text-xs opacity-60">{r.lastMessage}</span>}</Link>) : <p className="py-4 text-center text-xs opacity-55">Chưa có room. Hãy tạo room đầu tiên.</p>}</div>}</div>}
  </div>;
}
